### PR TITLE
Remove the (broken) imports to account.compat.

### PR DESCRIPTION
**Pull request by ntoll**
This branch introduces the same change other three files: `models.py`, `forms.py`, `views.py`.

In each case I've removed the broken import to `account.compat` and replaced it with something sane: references to the `d.c.a.User` model.

### CODE REVIEW

**Comment by jacobwegner** [comment]
@ntoll: `account.compat.get_user_modelt` was a wrapper around `django.contrib.auth.get_user_model` to allow support for Django 1.4, which didn't support a custom user model.

`django-user-accounts 1.1 ` raised the minimum requirement for Django to 1.7 and remove that wrapper

Rather than tying the models to the "standard" User model,  we can continue to support custom user models by importing `get_user_model` from `django.contrib.auth`.

**Comment by ntoll** [comment]
Hi @jacobwegner. Aha! That's what it was for..! Neither myself nor @jtauber could work out what a.c.get_user_model was for. I just guessed looking at the code. Far better to replace with d.c.a.get_user_mode (which I'll revise to use). Cheers!

**Comment by jtauber** [comment]
if DUA has raised the minimum to 1.7 then pinax-teams should too

**Comment by paltman** [comment]
:+1:

**Comment by miurahr** [comment]
Why not merge? CI fails are not caused by this.

**Comment by jtauber** [comment]
Made on trms branch.

**Pull request closed without merging**
