### PR TITLE
add a state for waitlisted

### PR DESCRIPTION
**Pull request by mikefranklin**

### CODE REVIEW

**Comment by paltman** [comment]
Instead of adding another state to this, I want to make this configurable from a setting.  I have been thinking about some ways to do this for a few days now.  Basically, making the `STATE_CHOICES` a setting and then in other places that are currently using `Membership.STATE_*` enum values, wrap logic in a hookset method that can also be overridden at the site level.

**Comment by gregnewman** [comment]
That's a good idea @paltman, with a default fallback in case the `STATE_CHOICES` are not configured, obviously.

**Comment by paltman** [comment]
That would be a fairly large change, though, so I'm fine on deferring it until later and accepting this change as is.

Given that I do think we need to think about some of the model methods.  What does this new state mean for methods such as `BaseMembership.accept` and `BaseMembership.reject` and others that check for the `STATE_APPLIED` state only.  Should they consider this new state?

**Comment by mikefranklin** [comment]
I find it all a bit confusing.  pinax-teams don't have a size, and don't have any indication for having a waitlist, and I don't understand how accept/reject would be able to determine a waitlist state without them.

the LMS Application view sets the state directly and saves, without calling the accept/reject methods, and I've added the waitlist logic there (since the course instance has the waitlist boolean + available spots).

**Comment by paltman** [comment]
Yup. This my initial reaction to wanting to make the state and state handling pluggable.

**Pull request merged**
